
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const baloo2 = localFont({
  src: "./fonts/Baloo2-VariableFont_wght.ttf",
  variable: "--font-baloo-2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Free Hands",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${baloo2.className} antialiased`}
      >
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
